"""rename address

Revision ID: 772b22e90bf9
Revises: d235e969af47
Create Date: 2024-01-27 00:13:58.116724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772b22e90bf9'
down_revision = 'd235e969af47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')

    # ### end Alembic commands ###
